name: Deploy

on:
  workflow_dispatch:

jobs:
  check-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "$DEPLOY_SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - name: Write hosts
        env:
          DEPLOY_KNOWN_HOSTS: ${{ vars.DEPLOY_KNOWN_HOSTS }}
        run: |
          printf '%s\n' "$DEPLOY_KNOWN_HOSTS" > ~/.ssh/known_hosts
      - name: Check server
        env:
          DEPLOY_HOST: ${{ vars.DEPLOY_HOST }}
        run:
          ssh deploy@$DEPLOY_HOST docker ps
